#!/usr/bin/env python
"""
Simple test for ML-driven Narrative API
Tests that:
1. The API works with real market data
2. Narratives are ML-driven (no mock values)
3. Unknown symbols return proper errors
"""

import requests
import json
import sys

BASE_URL = "http://localhost:8001"
NARRATIVE_ENDPOINT = f"{BASE_URL}/api/narrative/generate"

# Test cases
TEST_CASES = [
    {"symbol": "AAPL", "investor": "Balanced", "horizon": "medium_term"},
    {"symbol": "TSLA", "investor": "Aggressive", "horizon": "short_term"},
    {"symbol": "BRK.A", "investor": "Conservative", "horizon": "long_term"},
    {"symbol": "ICICIBANK.NS", "investor": "Balanced", "horizon": "medium_term"},
]

INVALID_CASES = [
    {"symbol": "INVALID_SYMBOL_XYZ", "investor": "Balanced", "horizon": "medium_term"},
    {"symbol": "XXX123", "investor": "Balanced", "horizon": "medium_term"},
]

def test_valid_symbols():
    """Test narrative generation for valid stocks"""
    print("\n" + "=" * 70)
    print("Testing valid stock symbols (should use ML model)")
    print("=" * 70)
    
    for test_case in TEST_CASES:
        symbol = test_case["symbol"]
        print(f"\n📊 Testing {symbol}...")
        
        payload = {
            "symbol": symbol,
            "investor_type": test_case["investor"],
            "investment_horizon": test_case["horizon"],
            "investment_goal": "Growth"
        }
        
        try:
            response = requests.post(NARRATIVE_ENDPOINT, json=payload, timeout=30)
            
            if response.status_code == 200:
                data = response.json()
                
                # Verify ML outputs exist
                sentiment = data.get("narrative", {}).get("sentiment")
                confidence = data.get("narrative", {}).get("confidence")
                conviction = data.get("narrative", {}).get("conviction")
                model = data.get("model_used")
                
                print(f"✅ {symbol}: {sentiment} (conf: {confidence}%) | {conviction} conviction")
                print(f"   Model: {model}")
                
                # Verify no mock values
                if confidence and conviction:
                    print(f"   ✓ ML-driven (not mock)")
                else:
                    print(f"   ❌ Missing ML outputs")
                    
            elif response.status_code in [404, 400]:
                print(f"⚠️  {symbol}: Data not available - {response.json().get('detail')}")
            else:
                print(f"❌ {symbol}: Error {response.status_code}")
                print(f"   {response.text[:200]}")
                
        except Exception as e:
            print(f"❌ {symbol}: Request failed - {str(e)[:100]}")

def test_invalid_symbols():
    """Test that invalid symbols return proper errors (NOT mock data)"""
    print("\n" + "=" * 70)
    print("Testing invalid symbols (should return clear error)")
    print("=" * 70)
    
    for test_case in INVALID_CASES:
        symbol = test_case["symbol"]
        print(f"\n🚫 Testing invalid: {symbol}...")
        
        payload = {
            "symbol": symbol,
            "investor_type": test_case["investor"],
            "investment_horizon": test_case["horizon"],
        }
        
        try:
            response = requests.post(NARRATIVE_ENDPOINT, json=payload, timeout=30)
            
            if response.status_code == 404 or response.status_code == 400:
                error = response.json().get("detail", "")
                print(f"✅ Correctly rejected with error:")
                print(f"   {error[:150]}")
            else:
                print(f"❌ Should have failed but got: {response.status_code}")
                
        except Exception as e:
            print(f"✅ Correctly failed: {str(e)[:100]}")

def test_model_loaded():
    """Verify the ML model is loaded"""
    print("\n" + "=" * 70)
    print("Checking ML model status")
    print("=" * 70)
    
    try:
        # Make a simple request and check model info
        response = requests.post(
            NARRATIVE_ENDPOINT, 
            json={
                "symbol": "AAPL",
                "investor_type": "Balanced",
                "investment_horizon": "medium_term"
            },
            timeout=30
        )
        
        if response.status_code == 200:
            data = response.json()
            model = data.get("model_used")
            explainability = data.get("explainability", {})
            
            print(f"✅ Model loaded: {model}")
            print(f"   Generated by: {explainability.get('generated_by')}")
            print(f"   Model info: {explainability.get('model_info')}")
        else:
            print(f"❌ Cannot verify - API returned {response.status_code}")
            
    except Exception as e:
        print(f"❌ Cannot verify - {str(e)[:100]}")

if __name__ == "__main__":
    print("\n" + "=" * 70)
    print("🤖 ML-DRIVEN NARRATIVE ENGINE TESTS")
    print("=" * 70)
    print(f"Testing endpoint: {NARRATIVE_ENDPOINT}")
    
    test_model_loaded()
    test_valid_symbols()
    test_invalid_symbols()
    
    print("\n" + "=" * 70)
    print("✅ Tests complete")
    print("=" * 70)
