import type { Metadata } from 'next'

import { Inter, Roboto_Mono } from 'next/font/google'
// Global CSS is imported in _app.tsx for Pages Router
// import '../styles/globals.css'

const geistSans = Inter({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Roboto_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

// Note: metadata export is only supported in app directory, not pages directory
// export const metadata: Metadata = {
//   title: 'Clerk Next.js Quickstart',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="flex justify-end items-center p-4 gap-4 h-16">
          {/* Auth removed */}
        </header>
        {children}
      </body>
    </html>
  )
}